export default {
	defaultLanguageKeys: {
		"back": "Назад",
		"dismissalPageTitle": "Завершення співпраці",
		"finishDismissalButton": "Завершити",
		"employeeFiredAlert": "Працівника звільнено",
		"errorWhileAssignmentAlert": "Помилка при оновленні інформації про звільнення працівника: ",
		"dismissalFormTitle": "Інформація про звільнення", 
		"dismissalInfoTitle": "Планування дати звільнення", 
		"dismissalInfoDescription": "Щоб вчасно оформити всі документи - вкажіть дату звільнення не раніше ніж за 7-14 календарних днів до останнього робочого дня працівника.", 
		"endDatePickerLabel": "Дата завершення роботи", 
		"dismissalReasonSelectLabel": "Причина звільнення", 
		"dismissalReasonSelectPlaceholder": "Емоційне вигорання",
		"dismissalReasonSelectOptionOther": "Інша причина",
		"otherReasonInputPlaceholder": "Введіть іншу причину",
		"responsiblePersonSelectLabel": "Відповідальний за звільнення",
		"responsiblePersonSelectPlaceholder": "Тарас Шевченко",

		"reasonDescription": "Опишіть причину звільнення",
		"dismissalModalTitle": "Звільнити працівника",
		"dismissalModalDescription1": "Закінчити співпрацю із працівником",
		"dismissalModalDescription2": "Його статус буде змінено на",
		"dismissalModalDescription3": "Екс-працівник",
		"dismissalModalCancelButton": "Ні, скасувати",
		"dismissalModalSubmitButton": "Так, звільнити",
	},

	enLanguageKeys: {
		"back": "Back",
		"dismissalPageTitle": "End of cooperation",
		"finishDismissalButton": "Complete",
		"employeeFiredAlert": "Employee has been dismissed",
		"errorWhileAssignmentAlert": "Error updating employee: ",
		"dismissalFormTitle": "Dismissal Information", 
		"dismissalInfoTitle": "Scheduling the termination date", 
		"dismissalInfoDescription": "To ensure timely processing of all documents, please specify the termination date no earlier than 7-14 calendar days before the employee's last working day.", 
		"endDatePickerLabel": "End Date", 
		"dismissalReasonSelectLabel": "Reason for Dismissal", 
		"dismissalReasonSelectOptionOther": "Another reason",
		"otherReasonInputPlaceholder": "Enter another reason",
		"responsiblePersonSelectLabel": "Responsible for dismissals",
		"responsiblePersonSelectPlaceholder": "Taras Shevchenko",

		"reasonDescription": "Опишіть причину звільнення",
		"dismissalModalTitle": "Звільнити працівника",
		"dismissalModalDescription1": "Закінчити співпрацю із працівником",
		"dismissalModalDescription2": "Його статус буде змінено на",
		"dismissalModalDescription3": "Екс-працівник",
		"dismissalModalCancelButton": "Ні, скасувати",
		"dismissalModalSubmitButton": "Так, звільнити",
	}
}