export default {
	defaultLanguageKeys: {
		"back": "Назад",
		"addUserPageTitle": "Новий працівник",
		"editUserInfoPageTitle": "Редагувати дані працівника",
		"editUserInfoButton": "Зберегти",
		"addUserButton": "Створити профіль",
		"editUserFormTitle": "Основна інформація",
		"userNameInputLabel": "Ім'я",
		"userNameInputPlaceholder": "Тарас",
		"userNameInputError": "Введіть коректне ім'я",
		"userSurnameInputLabel": "Прізвище",
		"userSurnameInputPlaceholder": "Шевченко",
		"userSurnameInputError": "Введіть прізвище",
		"userMiddlenameInputLabel": "По батькові",
		"userMiddlenameInputPlaceholder": "Григорович",
		"userMiddlenameInputError": "Введіть по батькові",
		"userPhoneInputLabel": "Номер телефону",
		"userPhoneInputPlaceholder": "+380 00 000 00 00",
		"userPhoneInputError": "Некоректний формат номеру",
		"userEmailInputLabel": "Пошта",
		"userEmailInputPlaceholder": "example@gmail.com",
		"userEmailInputError": "Некоректна пошта",
		"userSexSelectLabel": "Стать",
		"userSexSelectOptionMale": "Чоловіча",
		"userSexSelectOptionFemale": "Жіноча",
		"userSexSelectPlaceholder": "Чоловіча",
		"userSexSelectError": "Стать",
		"userBirthPickerLabel": "Дата народження",

		"identificationDataTitle": "Ідентифікаційні дані",
		"passportInputLabel": "Номер паспорта або ID-картки",
		"passportInputError": "Некоретний формат номеру паспорта або ID-картки",
		"taxNumberLabel": "ІПН",
		"taxNumberError": "Некоретний формат ІПН",
		"blacklistLabel": "Чорний список",
		"graylistLabel": "Сірий список",
		"dublicatedByEmailPersonAlert": "Користувач з таким e-mail існує",
		"dmsNotFindedAlert": "Користувача не найдено в DMS app",
		"newEployeeCreatedAlert": "Нового працівника створено",
		"eployeesDataUpdatedAlert": "Дані працівника оновлено",
		"modalExistedProfileFindedLabel": "Знайдено існуючий профіль в системі",
		"modalExistedProfileFindedDescription": "Працівник з такими даними вже є в системі",
		"modalRenewProfileButton": "Відновити профіль",
		"modalGotoProfileButton": "Перейти на профіль",
		"modalWarningTitle": "Обмеження для працевлаштування",
		"modalWarningBlacklistDescription": "Повторне працевлаштування працівників з чорного списку неможливе, згідно з політикою компанії",
		"modalAnotherPersonButton": "Це інша людина",
		"modalAnderstandButton": "Зрозуміло",
		"modalRenewAssignmentTitle": "Повторне працевлаштування",
		"modalDublicateProfileTitle": "Дублювання профілю",
		"modalDublicateProfileWarningDescription" : "Щоб уникнути дублювання профілю - рекомендуємо перейти на цей профіль і додати його до нової команди",
		"modalGraylistWarningDescription" : "Профіль працівника має статус 'сірий список'.\nПовторне працевлаштування можливе.",
		"modalCreateNewButton": "Ні, створити новий",
		"modalSubmitRenewalButton": "Так, відновити",
		"modalSubmitGotoButton": "Так, перейти",
	},

	enLanguageKeys: {
		"back": "Back",
		"addUserPageTitle": "New employee",
		"editUserInfoPageTitle": "Edit info about employee",
		"editUserInfoButton": "Save",
		"addUserButton": "Create profile",
		"editUserFormTitle": "Main information",
		"userNameInputLabel": "Name",
		"userNameInputPlaceholder": "Taras",
		"userNameInputError": "Enter a valid name",
		"userSurnameInputLabel": "Surname",
		"userSurnameInputPlaceholder": "Shevchenko",
		"userSurnameInputError": "Enter surname",
		"userMiddlenameInputLabel": "Middle name",
		"userMiddlenameInputPlaceholder": "Grygorovych",
		"userMiddlenameInputError": "Enter middle name",
		"userPhoneInputLabel": "Phone Number",
		"userPhoneInputPlaceholder": "+380 00 000 00 00",
		"userPhoneInputError": "Invalid format",
		"userEmailInputLabel": "E-mail",
		"userEmailInputPlaceholder": "example@gmail.com",
		"userEmailInputError": "Invalid format",
		"userSexSelectLabel": "Gender",
		"userSexSelectOptionMale": "Male",
		"userSexSelectOptionFemale": "Female",
		"userSexSelectPlaceholder": "Male",
		"userSexSelectError": "Gender",
		"userBirthPickerLabel": "Date of birth",

		"identificationDataTitle": "Ідентифікаційні дані",
		"passportInputLabel": "Номер паспорта або ID-картки",
		"passportInputError": "Некоретний формат номеру паспорта або ID-картки",
		"taxNumberLabel": "ІПН",
		"taxNumberError": "Некоретний формат ІПН",
		"blacklistLabel": "Чорний список",
		"graylistLabel": "Сірий список",
		"dublicatedByEmailPersonAlert": "Користувач з таким e-mail існує",
		"dmsNotFindedAlert": "Користувача не найдено в DMS app",
		"newEployeeCreatedAlert": "Нового працівника створено",
		"eployeesDataUpdatedAlert": "Дані працівника оновлено",
		"modalExistedProfileFindedLabel": "Знайдено існуючий профіль в системі",
		"modalExistedProfileFindedDescription": "Працівник з такими даними вже є в системі",
		"modalRenewProfileButton": "Відновити профіль",
		"modalGotoProfileButton": "Перейти на профіль",
		"modalWarningTitle": "Обмеження для працевлаштування",
		"modalWarningBlacklistDescription": "Повторне працевлаштування працівників з чорного списку неможливе, згідно з політикою компанії",
		"modalAnotherPersonButton": "Це інша людина",
		"modalAnderstandButton": "Зрозуміло",
		"modalRenewAssignmentTitle": "Повторне працевлаштування",
		"modalDublicateProfileTitle": "Дублювання профілю",
		"modalDublicateProfileWarningDescription" : "Щоб уникнути дублювання профілю - рекомендуємо перейти на цей профіль і додати його до нової команди",
		"modalGraylistWarningDescription" : "Профіль працівника має статус 'сірий список'.\nПовторне працевлаштування можливе.",
		"modalCreateNewButton": "Ні, створити новий",
		"modalSubmitRenewalButton": "Так, відновити",
		"modalSubmitGotoButton": "Так, перейти",
	}
}