export default {
	defaultLanguageKeys: {
		"back": "Назад",
		"attestationFormTitle": "Атестаційна форма",
		"prticipantCardTitle": "Учасник атестації",
		"endCooperationButton": "Завершити співпрацю",
		"sendFormButton": "Відправити форму",
		"checkListTitle": "Чекліст",
		"checkListDescription1": "Список обов'язкових критеріїв для атестації працівника. Для успішного проходження атестації необхідно підтвердити мінімум",
		"checkListDescription2": "пунктів",
		"endCooperationModalTitle": "Завершити співпрацю",
		"endCooperationModalDescription1": "Ця дія є незворотною. Після завершення співпраці статус стажера",
		"endCooperationModalDescription2": "буде змінено на",
		"endCooperationModalDescription3": "Екс-стажер",
		"endCooperationModalReasonTitle": "Причина звільнення",
		"endCooperationModalReasonHelper": "Це поле обовʼязкове до заповнення",
		"endCooperationModalCancelButton": "Ні,скасувати",
		"endCooperationModalSubmitButton": "Так, завершити",
	},

	enLanguageKeys: {
		"back": "Назад",
		"attestationFormTitle": "Атестаційна форма",
		"prticipantCardTitle": "Учасник атестації",
		"endCooperationButton": "Завершити співпрацю",
		"sendFormButton": "Відправити форму",
		"checkListTitle": "Чекліст",
		"checkListDescription1": "Список обов'язкових критеріїв для атестації працівника. Для успішного проходження атестації необхідно підтвердити мінімум",
		"checkListDescription2": "пунктів",
		"endCooperationModalTitle": "Завершити співпрацю",
		"endCooperationModalDescription1": "Ця дія є незворотною. Після завершення співпраці статус стажера",
		"endCooperationModalDescription2": "буде змінено на",
		"endCooperationModalDescription3": "Екс-стажер",
		"endCooperationModalReasonTitle": "Причина звільнення",
		"endCooperationModalReasonHelper": "Це поле обовʼязкове до заповнення",
		"endCooperationModalCancelButton": "Ні,скасувати",
		"endCooperationModalSubmitButton": "Так, завершити",
	}
}