export default {
	defaultLanguageKeys: {
		"back": "Назад",
		"infoTitle": "Інформація про місце роботи",
		"workgroupSelectLabel": "Робоча група",
		"workgroupSelectPlaceholder": "Meta4",
		"workPositionInputLabel": "Робоча позиція", 
		"workPositionInputPlaceholder": "Старший працівник кухні", 
		"accessRoleSelectLabel": "Права доступу в системі",
		"accessRoleSelectPlaceholder": "Користувач",
		"roleSelectLabel": "Посада",
		"roleSelectPlaceholder": "Офіціант",
		"managerSelectLabel": "Керівник",
		"managerSelectPlaceholder": "Іван Іванов",
		"typeOfEmploymentLabel": "Тип найму",
		"typeOfEmploymentPlaceholder": "ФОП",
		"startDateLabel": "Дата початку роботи",
		"startDatePlaceholder": "день/місяць/рік",
		"uploadPhotoLabel" : "Завантажити фото працівника",
		"uploadPhotoButton" : "Завантажити Фото",
		"trialTitle": "Випробувальний період",
		"trialCheckboxLabel": "Об'єднати випробувальний період з основним часом роботи",
		"trialCheckboxDescription": "Додати випробувальний період (стажування) для працівника та включити його у загальний період роботи",
		"trialDatePickerLabel": "Дата закінчення випробувального періоду",
		"adaptationTitle": "Адаптація Працівника",
		"adaptationManagerSelectLabel": "Відповідальний (-на) за адаптацію",
		"adaptationSelectPlaceholder": "Неділька Дмитро",
		"accessesTitle": "Налаштування Доступів",
		"accessEquipmentInputLabel": "Забезпечити працівника необхідною технікою",
		"accessEquipmentInputPlaceholder": "Наприклад: комп'ютер, монітор, клавіатура...",
		"accessGoogleAppSelectLabel": "Створити обліковий запис у Google Apps",
		"accessGoogleAppSelectPlaceholder": "Оберіть домен",
		"accessEmailGroupSelectLabel": "Включити до відповідних поштових груп",
		"accessEmailGroupSelectPlaceholder": "Оберіть поштові групи",
		"accessServerSelectLabel": "Надати відповідний доступ до серверів",
		"accessServerSelectPlaceholder": "Оберіть сервери",
		"access1CSelectLabel": "Надати відповідні доступи до 1С",
		"access1CSelectPlaceholder": "Оберіть 1С",
		"accessPassesSelectLabel": "Подати заявку на видачу перепустки до офісних приміщень",
		"accessPassesSelectPlaceholder": "Оберіть офісні приміщення",
		"accessJiraCheckboxLabel": "Надати доступ до середовища Jira",
		"accessJiraCheckboxPlaceholder": "Якщо команда веде там проєкти",
		"accessPowerBICheckboxLabel": "Надати доступ до середовища PowerBI",
		"accessPowerBICheckboxPlaceholder": "Якщо функціонал це передбачає",
		"accessCameraCheckboxLabel": "Надати доступ до системи відеонагляду",
		"accessCameraCheckboxPlaceholder": "Якщо функціонал це передбачає",
		"accessSpartaCheckboxLabel": "Надати доступ до Sparta",
		"accessSpartaCheckboxPlaceholder": "Клієнтська база Lokal, якщо функціонал це передбачає",
		"accessCleverstaffCheckboxLabel": "Надати доступ до платформи Cleverstaff",
		"accessCleverstaffCheckboxPlaceholder": "Рекрутинг, лише для керівників та ресторанного менеджементу",
		"accessClickUpCheckboxLabel": "Надати доступ до платформи Click-up",
		"accessClickUpCheckboxPlaceholder": "Співпраця з арт-відділом, лише для керівників та ресторанного менеджементу",
		"dropzoneTitle": "Завантажити фото",
		"dropzoneDescription1": "Клікни тут або перетягни фото для завантаження",
		"dropzoneDescription2": "Доступні формати для завантаження .jpg, .png. Максимальний розмір фото до 5MB",
		"dropzoneCancelButton": "Скасувати",
		"dropzoneContinueButton": "Продовжити",

		"editAssignmentTitle": "Редагувати команди",
		"saveAssignmentButton": "Зберегти",
		"accessToPOSTitle": "Доступ до POS-терміналу",
		"POSLabel": "PIN-код",
		"infoUpdatedSuccessAlert": "Інформація про місце роботи успішно оновлена",
		"infoNotUpdatedAlert": "Щось пішло не так під час оновлення",
	},

	enLanguageKeys: {
		"back": "Назад",
		"infoTitle": "Інформація про місце роботи",
		"workgroupSelectLabel": "Робоча група",
		"workgroupSelectPlaceholder": "Meta4",
		"workPositionInputLabel": "Робоча позиція", 
		"workPositionInputPlaceholder": "Старший працівник кухні", 
		"accessRoleSelectLabel": "Права доступу в системі",
		"accessRoleSelectPlaceholder": "Користувач",
		"roleSelectLabel": "Посада",
		"roleSelectPlaceholder": "Офіціант",
		"managerSelectLabel": "Керівник",
		"managerSelectPlaceholder": "Іван Іванов",
		"typeOfEmploymentLabel": "Тип найму",
		"typeOfEmploymentPlaceholder": "ФОП",
		"startDateLabel": "Дата початку роботи",
		"startDatePlaceholder": "день/місяць/рік",
		"uploadPhotoLabel" : "Завантажити фото працівника",
		"uploadPhotoButton" : "Завантажити Фото",
		"trialTitle": "Випробувальний період",
		"trialCheckboxLabel": "Об'єднати випробувальний період з основним часом роботи",
		"trialCheckboxDescription": "Додати випробувальний період (стажування) для працівника та включити його у загальний період роботи",
		"trialDatePickerLabel": "Дата закінчення випробувального періоду",
		"adaptationTitle": "Адаптація Працівника",
		"adaptationManagerSelectLabel": "Відповідальний (-на) за адаптацію",
		"adaptationSelectPlaceholder": "Неділька Дмитро",
		"accessesTitle": "Налаштування Доступів",
		"accessEquipmentInputLabel": "Забезпечити працівника необхідною технікою",
		"accessEquipmentInputPlaceholder": "Наприклад: комп'ютер, монітор, клавіатура...",
		"accessGoogleAppSelectLabel": "Створити обліковий запис у Google Apps",
		"accessGoogleAppSelectPlaceholder": "Оберіть домен",
		"accessEmailGroupSelectLabel": "Включити до відповідних поштових груп",
		"accessEmailGroupSelectPlaceholder": "Оберіть поштові групи",
		"accessServerSelectLabel": "Надати відповідний доступ до серверів",
		"accessServerSelectPlaceholder": "Оберіть сервери",
		"access1CSelectLabel": "Надати відповідні доступи до 1С",
		"access1CSelectPlaceholder": "Оберіть 1С",
		"accessPassesSelectLabel": "Подати заявку на видачу перепустки до офісних приміщень",
		"accessPassesSelectPlaceholder": "Оберіть офісні приміщення",
		"accessJiraCheckboxLabel": "Надати доступ до середовища Jira",
		"accessJiraCheckboxPlaceholder": "Якщо команда веде там проєкти",
		"accessPowerBICheckboxLabel": "Надати доступ до середовища PowerBI",
		"accessPowerBICheckboxPlaceholder": "Якщо функціонал це передбачає",
		"accessCameraCheckboxLabel": "Надати доступ до системи відеонагляду",
		"accessCameraCheckboxPlaceholder": "Якщо функціонал це передбачає",
		"accessSpartaCheckboxLabel": "Надати доступ до Sparta",
		"accessSpartaCheckboxPlaceholder": "Клієнтська база Lokal, якщо функціонал це передбачає",
		"accessCleverstaffCheckboxLabel": "Надати доступ до платформи Cleverstaff",
		"accessCleverstaffCheckboxPlaceholder": "Рекрутинг, лише для керівників та ресторанного менеджементу",
		"accessClickUpCheckboxLabel": "Надати доступ до платформи Click-up",
		"accessClickUpCheckboxPlaceholder": "Співпраця з арт-відділом, лише для керівників та ресторанного менеджементу",
		"dropzoneTitle": "Завантажити фото",
		"dropzoneDescription1": "Клікни тут або перетягни фото для завантаження",
		"dropzoneDescription2": "Доступні формати для завантаження .jpg, .png. Максимальний розмір фото до 5MB",
		"dropzoneCancelButton": "Скасувати",
		"dropzoneContinueButton": "Продовжити",

		"editAssignmentTitle": "Редагувати команди",
		"saveAssignmentButton": "Зберегти",
		"accessToPOSTitle": "Доступ до POS-терміналу",
		"POSLabel": "PIN-код",
		"infoUpdatedSuccessAlert": "Інформація про місце роботи успішно оновлена",
		"infoNotUpdatedAlert": "Щось пішло не так під час оновлення",
	},
}
