export default {
	defaultLanguageKeys: {
		"workgroupsTreeTitle": "Робочі групи",
		"orgChartTitle": "Люди",
		"addToTeamButton": "Додати в команду",
		"createProfileButton": "Створити профіль",
		"aesSortOption": "Сотувати за назвою А-Я",
		"descSortOption": "Сотувати за назвою Я-А",
		"positionSortOption": "Сотувати за Посадою",
		"editMenuOption": "Редагувати",
		"dismissalMenuOption": "Завершити співпрацю",
		"preparingToMakeFileAlert": "Готуємо файл до завантаження...",
		"exceededToMakeFileAlert": "Ви перевищили максимальну к-сть людей для завантаження",
		"downloadingFileAlert1": "Завантаження файлу",
		"downloadingFileAlert2": "розпочалось",
		"somethingWrongFileAlert": "Щось пішло не так під час завантаження файлу",
		"nameExelFile": "інфо_працівники",
		"nameExelInnerSheet": "Лист1",
	},

	enLanguageKeys: {
		"workgroupsTreeTitle": "Робочі групи",
		"orgChartTitle": "Люди",
		"addToTeamButton": "Додати в команду",
		"createProfileButton": "Створити профіль",
		"aesSortOption": "Сотувати за назвою А-Я",
		"descSortOption": "Сотувати за назвою Я-А",
		"positionSortOption": "Сотувати за Посадою",
		"editMenuOption": "Редагувати",
		"dismissalMenuOption": "Завершити співпрацю",
		"preparingToMakeFileAlert": "Готуємо файл до завантаження...",
		"exceededToMakeFileAlert": "Ви перевищили максимальну к-сть людей для завантаження",
		"downloadingFileAlert1": "Завантаження файлу",
		"downloadingFileAlert2": "розпочалось",
		"somethingWrongFileAlert": "Щось пішло не так під час завантаження файлу",
		"nameExelFile": "інфо_працівники",
		"nameExelInnerSheet": "Лист1",
	}
}