export default {
	defaultLanguageKeys: {
		"languageSelectOptionEn": "Англійська",
		"languageSelectOptionAr": "Арабська",
		"languageSelectOptionBn": "Бенгальська",
		"languageSelectOptionVi": "В'єтнамська",
		"languageSelectOptionHi": "Гінді",
		"languageSelectOptionEl": "Грецька",
		"languageSelectOptionHe": "Іврит",
		"languageSelectOptionId": "Індонезійська",
		"languageSelectOptionEs": "Іспанська",
		"languageSelectOptionIt": "Італійська",
		"languageSelectOptionZh": "Китайська",
		"languageSelectOptionKo": "Корейська",
		"languageSelectOptionMs": "Малайська",
		"languageSelectOptionNl": "Нідерландська",
		"languageSelectOptionDe": "Німецька",
		"languageSelectOptionNo": "Норвезька",
		"languageSelectOptionPl": "Польська",
		"languageSelectOptionPt": "Португальська",
		"languageSelectOptionTh": "Тайська",
		"languageSelectOptionTr": "Турецька",
		"languageSelectOptionUk": "Українська",
		"languageSelectOptionUr": "Урду",
		"languageSelectOptionFi": "Фінська",
		"languageSelectOptionFr": "Французька",
		"languageSelectOptionHr": "Хорватська",
		"languageSelectOptionCs": "Чеська",
		"languageSelectOptionSv": "Шведська",
		"languageSelectOptionJa": "Японська",

		"back": "Назад",
		"addUserPageTitle": "Новий працівник",
		"editUserInfoPageTitle": "Редагувати дані працівника",
		"editUserInfoButton": "Зберегти",
		"addUserButton": "Створити профіль",
		"editUserFormTitle": "Основна інформація",
		"userNameInputLabel": "Ім'я",
		"userNameInputPlaceholder": "Тарас",
		"userNameInputError": "Введіть коректне ім'я",
		"userSurnameInputLabel": "Прізвище",
		"userSurnameInputPlaceholder": "Шевченко",
		"userSurnameInputError": "Введіть прізвище",
		"userMiddlenameInputLabel": "По батькові",
		"userMiddlenameInputPlaceholder": "Григорович",
		"userMiddlenameInputError": "Введіть по батькові",
		"userPhoneInputLabel": "Номер телефону",
		"userPhoneInputPlaceholder": "+380 00 000 00 00",
		"userPhoneInputError": "Некоректний формат номеру",
		"userEmailInputLabel": "Пошта",
		"userEmailInputPlaceholder": "example@gmail.com",
		"userEmailInputError": "Некоректна пошта",
		"userSexSelectLabel": "Стать",
		"userSexSelectOptionMale": "Чоловіча",
		"userSexSelectOptionFemale": "Жіноча",
		"userSexSelectPlaceholder": "Чоловіча",
		"userSexSelectError": "Стать",
		"userBirthPickerLabel": "Дата народження",
		"treeTitle": "ПРОФІЛЬ",

		"identificationFormTitle": "Ідентифікаційні дані",
		"passportInputLabel": "Номер паспорта або ID-картки",
		"passportInputError": "Некоретний формат номеру паспорта або ID-картки",
		"taxNumberLabel": "ІПН",
		"taxNumberError": "Некоретний формат ІПН",
		"lokalCardInputLabel": "Номер картки Lokal",
		"militaryDocumentsSelectLabel": "Військово-обліковий документ",
		"militaryDocumentsSelectPlaceholder": "Оберіть зі списку",
		"militaryDocumentSelectOptionNew": "ВОД нового зразку з VIN-кодом",
		"militaryDocumentSelectOptionOld": "ВОД старого зразку",
		"militaryDocumentSelectOptionPrescriptive": "приписне посвідчення",
		"militaryDocumentSelectOptionNo": "відсутні документи",
		"registerAddress": "Адреса прописки",
		"residentialAddress": "Адреса проживання",
		"countryInputLabel" : "Країна",
		"countryInputPlaceholder" : "Україна",
		"cityInputLabel" : "Місто",
		"cityInputPlaceholder" : "Львів",
		"streetInputLabel" : "Вулиця",
		"streetInputPlaceholder" : "Печерська",
		"houseInputLabel" : "Будинок",
		"apartmentInputLabel" : "Квартира",
		"zipCodeInputLabel": "Поштовий індекс",
		"mergeAdressesCheckboxLabel": "Працівник проживає за місцем прописки",
		"mergeAdressesCheckboxDescription": "При вибору цієї опції дані адреси проживання заповняться автоматично відповідно до адреси прописки",
		"experienceFormTitle": "Попередній досвід",
		"workplaceTitle": "Місце праці",
		"addWorkplaceButton": "Додати місце праці",
		"workplaceNameInputLabel": "Назва компанії",
		"workplaceNameInputPlaceholder": "Компанія",
		"workplacePositionInputLabel": "Посада",
		"workplacePositionInputPlaceholder": "Директор продажів",
		"workplaceStartDateLabel": "Дата початку роботи",
		"workplaceEndDateLabel": "Дата кінця роботи",
		"familyFormTitle": "Сім'я",
		"addChildButton": "Додати дитину",
		"familyStatusSelectTitle": "Сімейний стан",
		"familyMarriedSelectOption": "Одружений/Одружена",
		"familyUnmarriedSelectOption": "Неодружений/Незаміжня",
		"familyChildrenCheckboxLabel": "Діти",
		"familyChildrenCheckboxDescription": "Позначте, щоб додати інформацію про дітей",
		"familyChildTitle": "Дитина",
		"familyChildNameInputLabel": "Ім'я дитини",
		"familyChildNameInputPlaceholder": "Максим",
		"familyChildBirthdayInputLabel": "Дата народження",
		"educationFormTitle": "Освіта",
		"educationTitle": "Навчальний заклад",
		"addEducationInstitutionButton": "Додати навчальний заклад",
		"educationInstitutionInputLabel": "Назва навчального закладу",
		"educationInstitutionInputPlaceholder": "Український католицький укніверситет",
		"educationSpecialityInputLabel": "Спеціальність",
		"educationSpecialityInputPlaceholder": "Журналіст",
		"educationlevelSelectLabel": "Рівень освіти",
		"educationLevelSelectOptionBachelor": "Неповна вища (Бакалавр)",
		"educationLevelSelectOptionMaster": "Повна вища (Магістр)",
		"coursesFormTitle": "Курси",
		"courseTitle": "Курс",
		"addCourseButton": "Додати курс",
		"courseNameInputLabel": "Назва курсу",
		"courseNameInputPlaceholder": "Курс баристи",
		"courseDatePickerLabel": "Дата здобуття",
		"languagesFormTitle": "Мови",
		"languagesTitle": "Мова",
		"addLanguageButton": "Додати мову",
		"languageInputPlaceholder": "Українська",
		"languageLevelSelectLabel": "Рівень знань",
		"languageLevelSelectPlaceholder": "С2 (Рідна мова)",	
		"languageLevelSelectOptionA1": "A1 (Початківець)",
		"languageLevelSelectOptionA2": "A2 (Елементарний)",
		"languageLevelSelectOptionB1": "B1 (Середній)",
		"languageLevelSelectOptionB2": "B2 (Вище середнього)",
		"languageLevelSelectOptionC1": "C1 (Просунутий)",
		"languageLevelSelectOptionC2": "C2 (Вільне володіння)",
		"additionalFormTitle": "Додаткова інформація",
		"driverLicenceSelectLabel": "Наявність водійських прав",
		"driverLicenceSelectOptionYes": "Так",
		"driverLicenceSelectOptionNo": "Ні",
		"comunityInputLable": "Приналежність до спільнот",
		"comunityInputPlaceholder": "Спілка українських підприємців (СУП)",
		"preferenceInputLabel": "Уподобання",
		"preferenceInputPlaceholder": "Квіти, малювання, спорт...",
		"pageEditedAlert1": "Сторінка",
		"pageEditedAlert2": "успішно оновлена",

		"educationLevelSelectOptionPHD": "Кандидат/Доктор наук",
		"educationLevelSelectOptionBachelorNotFinished": "Неповна вища (Незавершена)",
		"educationLevelSelectOptionCollege": "Професійно-технічна",
		"educationLevelSelectOptionSchool": "Середня (Школа)",
	},

	enLanguageKeys: {
		"languageSelectOptionEn": "English",
		"languageSelectOptionAr": "Arabic",
		"languageSelectOptionBn": "Bengali",
		"languageSelectOptionVi": "Vietnamese",
		"languageSelectOptionHi": "Hindi",
		"languageSelectOptionEl": "Greek",
		"languageSelectOptionHe": "Hebrew",
		"languageSelectOptionId": "Indonesian",
		"languageSelectOptionEs": "Spanish",
		"languageSelectOptionIt": "Italian",
		"languageSelectOptionZh": "Chinese",
		"languageSelectOptionKo": "Korean",
		"languageSelectOptionMs": "Malay",
		"languageSelectOptionNl": "Dutch",
		"languageSelectOptionDe": "German",
		"languageSelectOptionNo": "Norwegian",
		"languageSelectOptionPl": "Polish",
		"languageSelectOptionPt": "Portuguese",
		"languageSelectOptionTh": "Thai",
		"languageSelectOptionTr": "Turkish",
		"languageSelectOptionUk": "Ukrainian",
		"languageSelectOptionUr": "Urdu",
		"languageSelectOptionFi": "Finnish",
		"languageSelectOptionFr": "French",
		"languageSelectOptionHr": "Croatian",
		"languageSelectOptionCs": "Czech",
		"languageSelectOptionSv": "Swedish",
		"languageSelectOptionJa": "Japanese",

		"back": "Назад",
		"addUserPageTitle": "Новий працівник",
		"editUserInfoPageTitle": "Редагувати дані працівника",
		"editUserInfoButton": "Зберегти",
		"addUserButton": "Створити профіль",
		"editUserFormTitle": "Основна інформація",
		"userNameInputLabel": "Ім'я",
		"userNameInputPlaceholder": "Тарас",
		"userNameInputError": "Введіть коректне ім'я",
		"userSurnameInputLabel": "Прізвище",
		"userSurnameInputPlaceholder": "Шевченко",
		"userSurnameInputError": "Введіть прізвище",
		"userMiddlenameInputLabel": "По батькові",
		"userMiddlenameInputPlaceholder": "Григорович",
		"userMiddlenameInputError": "Введіть по батькові",
		"userPhoneInputLabel": "Номер телефону",
		"userPhoneInputPlaceholder": "+380 00 000 00 00",
		"userPhoneInputError": "Некоректний формат номеру",
		"userEmailInputLabel": "Пошта",
		"userEmailInputPlaceholder": "example@gmail.com",
		"userEmailInputError": "Некоректна пошта",
		"userSexSelectLabel": "Стать",
		"userSexSelectOptionMale": "Чоловіча",
		"userSexSelectOptionFemale": "Жіноча",
		"userSexSelectPlaceholder": "Чоловіча",
		"userSexSelectError": "Стать",
		"userBirthPickerLabel": "Дата народження",
		"treeTitle": "ПРОФІЛЬ",

		"identificationFormTitle": "Ідентифікаційні дані",
		"passportInputLabel": "Номер паспорта або ID-картки",
		"passportInputError": "Некоретний формат номеру паспорта або ID-картки",
		"taxNumberLabel": "ІПН",
		"taxNumberError": "Некоретний формат ІПН",
		"lokalCardInputLabel": "Номер картки Lokal",
		"militaryDocumentsSelectLabel": "Військово-обліковий документ",
		"militaryDocumentsSelectPlaceholder": "Оберіть зі списку",
		"militaryDocumentSelectOptionNew": "ВОД нового зразку з VIN-кодом",
		"militaryDocumentSelectOptionOld": "ВОД старого зразку",
		"militaryDocumentSelectOptionPrescriptive": "приписне посвідчення",
		"militaryDocumentSelectOptionNo": "відсутні документи",
		"registerAddress": "Адреса прописки",
		"residentialAddress": "Адреса проживання",
		"countryInputLabel" : "Країна",
		"countryInputPlaceholder" : "Україна",
		"cityInputLabel" : "Місто",
		"cityInputPlaceholder" : "Львів",
		"streetInputLabel" : "Вулиця",
		"streetInputPlaceholder" : "Печерська",
		"houseInputLabel" : "Будинок",
		"apartmentInputLabel" : "Квартира",
		"zipCodeInputLabel": "Поштовий індекс",
		"mergeAdressesCheckboxLabel": "Працівник проживає за місцем прописки",
		"mergeAdressesCheckboxDescription": "При вибору цієї опції дані адреси проживання заповняться автоматично відповідно до адреси прописки",
		"experienceFormTitle": "Попередній досвід",
		"workplaceTitle": "Місце праці",
		"addWorkplaceButton": "Додати місце праці",
		"workplaceNameInputLabel": "Назва компанії",
		"workplaceNameInputPlaceholder": "Компанія",
		"workplacePositionInputLabel": "Посада",
		"workplacePositionInputPlaceholder": "Директор продажів",
		"workplaceStartDateLabel": "Дата початку роботи",
		"workplaceEndDateLabel": "Дата кінця роботи",
		"familyFormTitle": "Сім'я",
		"addChildButton": "Додати дитину",
		"familyStatusSelectTitle": "Сімейний стан",
		"familyMarriedSelectOption": "Одружений/Одружена",
		"familyUnmarriedSelectOption": "Неодружений/Незаміжня",
		"familyChildrenCheckboxLabel": "Діти",
		"familyChildrenCheckboxDescription": "Позначте, щоб додати інформацію про дітей",
		"familyChildTitle": "Дитина",
		"familyChildNameInputLabel": "Ім'я дитини",
		"familyChildNameInputPlaceholder": "Максим",
		"familyChildBirthdayInputLabel": "Дата народження",
		"educationFormTitle": "Освіта",
		"educationTitle": "Навчальний заклад",
		"addEducationInstitutionButton": "Додати навчальний заклад",
		"educationInstitutionInputLabel": "Назва навчального закладу",
		"educationInstitutionInputPlaceholder": "Український католицький укніверситет",
		"educationSpecialityInputLabel": "Спеціальність",
		"educationSpecialityInputPlaceholder": "Журналіст",
		"educationlevelSelectLabel": "Рівень освіти",
		"educationLevelSelectOptionBachelor": "Неповна вища (Бакалавр)",
		"educationLevelSelectOptionMaster": "Повна вища (Магістр)",
		"coursesFormTitle": "Курси",
		"courseTitle": "Курс",
		"addCourseButton": "Додати курс",
		"courseNameInputLabel": "Назва курсу",
		"courseNameInputPlaceholder": "Курс баристи",
		"courseDatePickerLabel": "Дата здобуття",
		"languagesFormTitle": "Мови",
		"languagesTitle": "Мова",
		"addLanguageButton": "Додати мову",
		"languageInputPlaceholder": "Українська",
		"languageLevelSelectLabel": "Рівень знань",
		"languageLevelSelectPlaceholder": "С2 (Рідна мова)",	
		"languageLevelSelectOptionA1": "A1 (Початківець)",
		"languageLevelSelectOptionA2": "A2 (Елементарний)",
		"languageLevelSelectOptionB1": "B1 (Середній)",
		"languageLevelSelectOptionB2": "B2 (Вище середнього)",
		"languageLevelSelectOptionC1": "C1 (Просунутий)",
		"languageLevelSelectOptionC2": "C2 (Вільне володіння)",
		"additionalFormTitle": "Додаткова інформація",
		"driverLicenceSelectLabel": "Наявність водійських прав",
		"driverLicenceSelectOptionYes": "Так",
		"driverLicenceSelectOptionNo": "Ні",
		"comunityInputLable": "Приналежність до спільнот",
		"comunityInputPlaceholder": "Спілка українських підприємців (СУП)",
		"preferenceInputLabel": "Уподобання",
		"preferenceInputPlaceholder": "Квіти, малювання, спорт...",
		"pageEditedAlert1": "Сторінка",
		"pageEditedAlert2": "успішно оновлена",

		"educationLevelSelectOptionPHD": "Кандидат/Доктор наук",
		"educationLevelSelectOptionBachelorNotFinished": "Неповна вища (Незавершена)",
		"educationLevelSelectOptionCollege": "Професійно-технічна",
		"educationLevelSelectOptionSchool": "Середня (Школа)",
	}
}