export default {
	defaultLanguageKeys: {
		"back": "Назад",
		"Waiting_ListPageTitle": "Список очікування",
		"unassignedListDescription": "Список нових співробітників, які очікують на додавання в команди",
		"addEmployeeButton": "Додати працівника",
		"newEmployeeLabel": "новий",
		"addToTeamButton": "До команди",
		"asc": "Сортувати за назвою А-Я",
		"desc": "Сортувати за назвою Я-А",

		"addProfileButton": "Створити профіль",
		"ascDateSortOption": "За датою (від старих до нових)",
		"descDateSortOption": "За датою (від нових до старих)",
		"dismissalModalTitle": "Видалити працівника",
		"dismissalModalDescription1": "Працівник",
		"dismissalModalDescription2": "буде видалено з списку, і його не можна буде відновити",
		"dismissaLModalCancelButton": "Скасувати",
		"dismissaLModalSubmitButton": "Видалити",
		"tipTitle": "Деякі працівники ще не в команді",
		"tipDescription": "Додайте їх, щоб система та її функції стали доступними для них",
		"tipCloseButton": "Закрити",
		"tipActionDescription": "Більше не показувати",
		"peopleDeletedSuccessAlert": "People Deleted",
		"peopleDeletionErrorALert": "Error: People not found or could not be deleted",
		"checkInfoWarningTitle": "Перевірте дані",
		"checkInfoWarningDescription": "Після створення профілю, змінити ці дані буде неможливо. Введіть їх уважно",
	},

	enLanguageKeys: {
		"back": "Back",
		"Waiting_ListPageTitle": "Waiting list",
		"unassignedListDescription": "Upcoming team members",
		"addEmployeeButton": "Add employee",
		"newEmployeeLabel": "New",
		"addToTeamButton": "To a team",
		"asc": "Sort by name A-Z",
		"desc": "Sort by name Z-A",

		"addProfileButton": "Створити профіль",
		"ascDateSortOption": "За датою (від старих до нових)",
		"descDateSortOption": "За датою (від нових до старих)",
		"dismissalModalTitle": "Видалити працівника",
		"dismissalModalDescription1": "Працівник",
		"dismissalModalDescription2": "буде видалено з списку, і його не можна буде відновити",
		"dismissaLModalCancelButton": "Скасувати",
		"dismissaLModalSubmitButton": "Видалити",
		"tipTitle": "Деякі працівники ще не в команді",
		"tipDescription": "Додайте їх, щоб система та її функції стали доступними для них",
		"tipCloseButton": "Закрити",
		"tipActionDescription": "Більше не показувати",
		"peopleDeletedSuccessAlert": "People Deleted",
		"peopleDeletionErrorALert": "Error: People not found or could not be deleted",
		"checkInfoWarningTitle": "Перевірте дані",
		"checkInfoWarningDescription": "Після створення профілю, змінити ці дані буде неможливо. Введіть їх уважно",
	}
}