export default {
	defaultLanguageKeys: {
		"back": "Назад",
		"adaptationFormTitle": "Адаптаційна форма",
		"prticipantCardTitle": "Учасник адаптаційної програми",
		"endCooperationButton": "Завершити співпрацю",
		"saveButton": "Зберегти",
		"sendFormButton": "Відправити форму",
		"checkListTitle": "Чекліст",
		"checkListDescription": "Список обов'язкових завдань для успішної адаптації працівника. Процес вважатиметься завершеним, коли всі завдання будуть виконані",
		"endCooperationModalTitle": "Завершити співпрацю",
		"endCooperationModalDescription1": "Ця дія є незворотною. Після завершення співпраці статус стажера",
		"endCooperationModalDescription2": "буде змінено на",
		"endCooperationModalDescription3": "Екс-стажер",
		"endCooperationModalReasonTitle": "Причина звільнення",
		"endCooperationModalReasonHelper": "Це поле обовʼязкове до заповнення",
		"endCooperationModalCancelButton": "Ні,скасувати",
		"endCooperationModalSubmitButton": "Так, завершити",
	},

	enLanguageKeys: {
		"back": "Назад",
		"adaptationFormTitle": "Адаптаційна форма",
		"prticipantCardTitle": "Учасник адаптаційної програми",
		"endCooperationButton": "Завершити співпрацю",
		"saveButton": "Зберегти",
		"sendFormButton": "Відправити форму",
		"checkListTitle": "Чекліст",
		"checkListDescription": "Список обов'язкових завдань для успішної адаптації працівника. Процес вважатиметься завершеним, коли всі завдання будуть виконані",
		"endCooperationModalTitle": "Завершити співпрацю",
		"endCooperationModalDescription1": "Ця дія є незворотною. Після завершення співпраці статус стажера",
		"endCooperationModalDescription2": "буде змінено на",
		"endCooperationModalDescription3": "Екс-стажер",
		"endCooperationModalReasonTitle": "Причина звільнення",
		"endCooperationModalReasonHelper": "Це поле обовʼязкове до заповнення",
		"endCooperationModalCancelButton": "Ні,скасувати",
		"endCooperationModalSubmitButton": "Так, завершити",
	}
}