export default {
	defaultLanguageKeys: {
		"monthOptionJan": "січня",
		"monthOptionFeb": "лютого",
		"monthOptionMar": "березня",
		"monthOptionAp": "квітня",
		"monthOptionMay": "травня",
		"monthOptionJun": "червня",
		"monthOptionJul": "липня",
		"monthOptionAu": "серпня",
		"monthOptionSep": "вересня",
		"monthOptionOct": "жовтня",
		"monthOptionNov": "листопада",
		"monthOptionDec": "грудня",
		"languageSelectOptionEn": "Англійська",
		"languageSelectOptionAr": "Арабська",
		"languageSelectOptionBn": "Бенгальська",
		"languageSelectOptionVi": "В'єтнамська",
		"languageSelectOptionHi": "Гінді",
		"languageSelectOptionEl": "Грецька",
		"languageSelectOptionHe": "Іврит",
		"languageSelectOptionId": "Індонезійська",
		"languageSelectOptionEs": "Іспанська",
		"languageSelectOptionIt": "Італійська",
		"languageSelectOptionZh": "Китайська",
		"languageSelectOptionKo": "Корейська",
		"languageSelectOptionMs": "Малайська",
		"languageSelectOptionNl": "Нідерландська",
		"languageSelectOptionDe": "Німецька",
		"languageSelectOptionNo": "Норвезька",
		"languageSelectOptionPl": "Польська",
		"languageSelectOptionPt": "Португальська",
		"languageSelectOptionTh": "Тайська",
		"languageSelectOptionTr": "Турецька",
		"languageSelectOptionUk": "Українська",
		"languageSelectOptionUr": "Урду",
		"languageSelectOptionFi": "Фінська",
		"languageSelectOptionFr": "Французька",
		"languageSelectOptionHr": "Хорватська",
		"languageSelectOptionCs": "Чеська",
		"languageSelectOptionSv": "Шведська",
		"languageSelectOptionJa": "Японська",

		"thirdWarning /greyList": "3-є попередження(сірий спиок)",
		"blacklist ": "Зловживання (чорний список)",
		"physicalLoad": "Завелике фізичне навантаження",
		"health": "Стан здоров'я",
		"mobilization": "Мобілізація",
		"profession": "Робота по спеціальності",
		"education": "Навчання/сесія",
		"burnout": "Емоційне вигорання",
		"schedule ": "Графік роботи",
		"salary": "Оплата",
		"abroad": "Переїзд за кордон",
		"location": "Локація",
		"otherCity": "Переїзд в інше місто",
		"newCompany": "Робота в іншій компанії",
		"rotation": "Подати в ротацію",

		"back": "Назад",
		"profileTitle": "Профіль",
		"adaptationFormButton": "Адаптаційна форма",
		"attestationFormButton": "Атестаційна форма",
		"dismissalFormButton": "Форма звільнення",
		"undefined": "Невизначено",
		"unknown": "Невідомо",
		"locations": "Локації",
		"dateNotSpecified": "Дата не вказана",
		"incorrectDateFormat": "Неправильний формат дати",
		"positionLabel": "Посада / Позиція",
		"phoneNumberLabel": "Номер телефону",
		"workEmailLabel": "Робоча ел. пошта",
		"startDateLabel": "Почав працювати",
		"birthdayDateLabel": "Дата народження",
		"holdingExperienceLabel": "Стаж у холдингу",
		"editProfileButton": "Редагувати профіль",
		"addPhotoButton": "Додати фото профілю",
		"editPhotoButton": "Редагувати фото профілю",
		"extendedInfoTab": "Розширена інформація",
		"teamsTab": "Команди",
		"historyTeamsTab": "Історія команд",
		"skillsTab": "Знання та навички",
		"compensationTab": "Компенсація",
		"goalsTab": "Цілі",
		"achievementsTab": "Досягнення",
		"identificationTitle": "Ідентифікаційні дані",
		"taxNumber": "ІПН",
		"passport": "Номер паспорта",
		"localCard": "Номер картки Lokal",
		"militaryData": "Військово-облікові дані",
		"personalEmail": "Особиста ел. пошта",
		"registerAddress": "Адреса прописки",
		"residentialAddress": "Адреса проживання",
		"maritalStatus": "Сімейний стан",
		"children": "Діти",
		"yesOption": "Так",
		"noOption": "Ні",
		"marriedOption": "Одружений",
		"unmarriedOption": "Неодружений",
		"previousExperienceTitle": "Попередній досвід",
		"educationTitle": "Освіта",
		"speciality": "Спеціальність",
		"educationLevel": "Рівень освіти",
		"coursesTitle": "Курси",
		"finishCourseDate": "Дата здобуття",
		"languagesTitle": "Мови",
		"languageLevel": "Рівень знання",
		"familyTitle": "Сім'я",
		"additionalInfoTitle": "Додаткова інформація",
		"driverLicense": "Наявність водійський прав",
		"communities": "Спільноти",
		"preference": "Уподобання",
		"addToTeamButton": "Додати до команди",
		"LocationForRole": "Локація для цієї ролі",
		"roleDuration": "Стаж на цій ролі",
		"manger": "Керівник",
		"editMenuOption": "Редагувати",
		"editSubstitutionMenuOption": "Редагувати заміну",
		"makeMainMenuOption":"Зробити основним",
		"dismissalMenuOption": "Завершити співпрацю",
		"dismissalEmployeeMenuOption": "Звільнити працівника",
		"rotationMenuOption": "Подати в ротацію",
		"replacementMenuOption": "Заміна",
		"previousWorkPlacesMenuOption":"Попередні місця праці",
		"daysProgressLabel": "дні",
		"monthProgressLabel": "місяці",
		"uploadPhotoTitle": "Завантажити фото",
		"uploadPhotoInfo": "Доступні формати для завантаження .jpg, .png. Максимальний розмір фото до 5MB",
		"uploadPhotoDropzoneInfo": "Клікніть сюди або перетягніть фото для завантаження",
		"cancelButton": "Скасувати",
		"continueButton": "Продовжити",
		"warningGrayListTitle": "Повторне працевлаштування",
		"warningGrayListDescription": "Профіль працівника має статус <сірий список>. Повторне працевлаштування можливе, але може вимагати погодження або дотримання певних умов згідно з політикою компанії. Будь ласка, зверніться до відділу кадрів для отримання детальної інформації.",
		"warningBlackListTitle": "Обмеження для працевлаштування",
		"warningBlackListDescription": "Повторне працевлаштування працівників з чорного списку неможливе, згідно з політикою компанії",
		"uploadPhotoSuccessAlert": "Photo uploaded successfully",
		"uploadPhotoWrongAlert": "Something went wrong while uploading the photo. Please try again.",
		"addButton": "Додати",
		"substitutionMenuOptionLabel": "Заміна",
		"historyMenuOptionLabel": "Попередні місця праці",

		"languageLevelSelectOptionA1": "A1 (Початківець)",
		"languageLevelSelectOptionA2": "A2 (Елементарний)",
		"languageLevelSelectOptionB1": "B1 (Середній)",
		"languageLevelSelectOptionB2": "B2 (Вище середнього)",
		"languageLevelSelectOptionC1": "C1 (Просунутий)",
		"languageLevelSelectOptionC2": "C2 (Вільне володіння)",
		"educationLevelSelectOptionBachelor": "Неповна вища (Бакалавр)",
		"educationLevelSelectOptionMaster": "Повна вища (Магістр)",
		"endCooperationModalTitle": "Завершити співпрацю",
		"endCooperationModalDescription1": "Ця дія є незворотною. Після завершення співпраці статус стажера",
		"endCooperationModalDescription2": "буде змінено на",
		"endCooperationModalDescription3": "Екс-стажер",
		"endCooperationModalReasonTitle": "Причина звільнення",
		"endCooperationModalReasonHelper": "Це поле обовʼязкове до заповнення",
		"endCooperationModalCancelButton": "Ні,скасувати",
		"endCooperationModalSubmitButton": "Так, завершити",

		"closedAssignmentReasonLabel": "Звільнений через",
		"closedAssignmentStartDateLabel": "Початок роботи",
		"closedAssignmentEndDateLabel": "Кінець роботи",
		"comment": "Коментар",
		"educationLevelSelectOptionPHD": "Кандидат/Доктор наук", 
		"educationLevelSelectOptionBachelorNotFinished": "Неповна вища (Незавершена)", 
		"educationLevelSelectOptionCollege": "Професійно-технічна", 
		"educationLevelSelectOptionSchool": "Середня (Школа)", 
	},

	enLanguageKeys: {
		"monthOptionJan": "January",
		"monthOptionFeb": "February",
		"monthOptionMar": "March",
		"monthOptionAp": "April",
		"monthOptionMay": "May",
		"monthOptionJun": "June",
		"monthOptionJul": "July",
		"monthOptionAu": "August",
		"monthOptionSep": "September",
		"monthOptionOct": "October",
		"monthOptionNov": "November",
		"monthOptionDec": "December",
		"languageSelectOptionEn": "English",
		"languageSelectOptionAr": "Arabic",
		"languageSelectOptionBn": "Bengali",
		"languageSelectOptionVi": "Vietnamese",
		"languageSelectOptionHi": "Hindi",
		"languageSelectOptionEl": "Greek",
		"languageSelectOptionHe": "Hebrew",
		"languageSelectOptionId": "Indonesian",
		"languageSelectOptionEs": "Spanish",
		"languageSelectOptionIt": "Italian",
		"languageSelectOptionZh": "Chinese",
		"languageSelectOptionKo": "Korean",
		"languageSelectOptionMs": "Malay",
		"languageSelectOptionNl": "Dutch",
		"languageSelectOptionDe": "German",
		"languageSelectOptionNo": "Norwegian",
		"languageSelectOptionPl": "Polish",
		"languageSelectOptionPt": "Portuguese",
		"languageSelectOptionTh": "Thai",
		"languageSelectOptionTr": "Turkish",
		"languageSelectOptionUk": "Ukrainian",
		"languageSelectOptionUr": "Urdu",
		"languageSelectOptionFi": "Finnish",
		"languageSelectOptionFr": "French",
		"languageSelectOptionHr": "Croatian",
		"languageSelectOptionCs": "Czech",
		"languageSelectOptionSv": "Swedish",
		"languageSelectOptionJa": "Japanese",

		"thirdWarning /greyList": "3-є попередження(сірий спиок)",
		"blacklist ": "Зловживання (чорний список)",
		"physicalLoad": "Завелике фізичне навантаження",
		"health": "Стан здоров'я",
		"mobilization": "Мобілізація",
		"profession": "Робота по спеціальності",
		"education": "Навчання/сесія",
		"burnout": "Емоційне вигорання",
		"schedule ": "Графік роботи",
		"salary": "Оплата",
		"abroad": "Переїзд за кордон",
		"location": "Локація",
		"otherCity": "Переїзд в інше місто",
		"newCompany": "Робота в іншій компанії",
		"rotation": "Подати в ротацію",

		"back": "Назад",
		"profileTitle": "Профіль",
		"adaptationFormButton": "Адаптаційна форма",
		"attestationFormButton": "Атестаційна форма",
		"dismissalFormButton": "Форма звільнення",
		"undefined": "Невизначено",
		"unknown": "Невідомо",
		"locations": "Локації",
		"dateNotSpecified": "Дата не вказана",
		"incorrectDateFormat": "Неправильний формат дати",
		"positionLabel": "Посада / Позиція",
		"phoneNumberLabel": "Номер телефону",
		"workEmailLabel": "Робоча ел. пошта",
		"startDateLabel": "Почав працювати",
		"birthdayDateLabel": "Дата народження",
		"holdingExperienceLabel": "Стаж у холдингу",
		"editProfileButton": "Редагувати профіль",
		"addPhotoButton": "Додати фото профілю",
		"editPhotoButton": "Редагувати фото профілю",
		"extendedInfoTab": "Розширена інформація",
		"teamsTab": "Команди",
		"historyTeamsTab": "Історія команд",
		"skillsTab": "Знання та навички",
		"compensationTab": "Компенсація",
		"goalsTab": "Цілі",
		"achievementsTab": "Досягнення",
		"identificationTitle": "Ідентифікаційні дані",
		"taxNumber": "ІПН",
		"passport": "Номер паспорта",
		"localCard": "Номер картки Lokal",
		"militaryData": "Військово-облікові дані",
		"personalEmail": "Особиста ел. пошта",
		"registerAddress": "Адреса прописки",
		"residentialAddress": "Адреса проживання",
		"maritalStatus": "Сімейний стан",
		"children": "Діти",
		"yesOption": "Так",
		"noOption": "Ні",
		"marriedOption": "Одружений",
		"unmarriedOption": "Неодружений",
		"previousExperienceTitle": "Попередній досвід",
		"educationTitle": "Освіта",
		"speciality": "Спеціальність",
		"educationLevel": "Рівень освіти",
		"coursesTitle": "Курси",
		"finishCourseDate": "Дата здобуття",
		"languagesTitle": "Мови",
		"languageLevel": "Рівень знання",
		"familyTitle": "Сім'я",
		"additionalInfoTitle": "Додаткова інформація",
		"driverLicense": "Наявність водійський прав",
		"communities": "Спільноти",
		"preference": "Уподобання",
		"addToTeamButton": "Додати до команди",
		"LocationForRole": "Локація для цієї ролі",
		"roleDuration": "Стаж на цій ролі",
		"manger": "Керівник",
		"editMenuOption": "Редагувати",
		"editSubstitutionMenuOption": "Редагувати заміну",
		"makeMainMenuOption":"Зробити основним",
		"dismissalMenuOption": "Завершити співпрацю",
		"dismissalEmployeeMenuOption": "Звільнити працівника",
		"rotationMenuOption": "Подати в ротацію",
		"replacementMenuOption": "Заміна",
		"previousWorkPlacesMenuOption":"Попередні місця праці",
		"daysProgressLabel": "дні",
		"monthProgressLabel": "місяці",
		"uploadPhotoTitle": "Завантажити фото",
		"uploadPhotoInfo": "Доступні формати для завантаження .jpg, .png. Максимальний розмір фото до 5MB",
		"uploadPhotoDropzoneInfo": "Клікніть сюди або перетягніть фото для завантаження",
		"cancelButton": "Скасувати",
		"continueButton": "Продовжити",
		"warningGrayListTitle": "Повторне працевлаштування",
		"warningGrayListDescription": "Профіль працівника має статус <сірий список>. Повторне працевлаштування можливе, але може вимагати погодження або дотримання певних умов згідно з політикою компанії. Будь ласка, зверніться до відділу кадрів для отримання детальної інформації.",
		"warningBlackListTitle": "Обмеження для працевлаштування",
		"warningBlackListDescription": "Повторне працевлаштування працівників з чорного списку неможливе, згідно з політикою компанії",
		"uploadPhotoSuccessAlert": "Photo uploaded successfully",
		"uploadPhotoWrongAlert": "Something went wrong while uploading the photo. Please try again.",
		"addButton": "Додати",
		"substitutionMenuOptionLabel": "Заміна",
		"historyMenuOptionLabel": "Попередні місця праці",

		"languageLevelSelectOptionA1": "A1 (Початківець)",
		"languageLevelSelectOptionA2": "A2 (Елементарний)",
		"languageLevelSelectOptionB1": "B1 (Середній)",
		"languageLevelSelectOptionB2": "B2 (Вище середнього)",
		"languageLevelSelectOptionC1": "C1 (Просунутий)",
		"languageLevelSelectOptionC2": "C2 (Вільне володіння)",
		"educationLevelSelectOptionBachelor": "Неповна вища (Бакалавр)",
		"educationLevelSelectOptionMaster": "Повна вища (Магістр)",
		"endCooperationModalTitle": "Завершити співпрацю",
		"endCooperationModalDescription1": "Ця дія є незворотною. Після завершення співпраці статус стажера",
		"endCooperationModalDescription2": "буде змінено на",
		"endCooperationModalDescription3": "Екс-стажер",
		"endCooperationModalReasonTitle": "Причина звільнення",
		"endCooperationModalReasonHelper": "Це поле обовʼязкове до заповнення",
		"endCooperationModalCancelButton": "Ні,скасувати",
		"endCooperationModalSubmitButton": "Так, завершити",

		"closedAssignmentReasonLabel": "Звільнений через",
		"closedAssignmentStartDateLabel": "Початок роботи",
		"closedAssignmentEndDateLabel": "Кінець роботи:",
		"comment": "Коментар",
		"educationLevelSelectOptionPHD": "Кандидат/Доктор наук", 
		"educationLevelSelectOptionBachelorNotFinished": "Неповна вища (Незавершена)", 
		"educationLevelSelectOptionCollege": "Професійно-технічна", 
		"educationLevelSelectOptionSchool": "Середня (Школа)", 
	}
}